version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/opt/www
    ports:
      - "9501:9501"
      - "9502:9502"
    depends_on:
      - redis
      - mongo
      - mysql
    privileged: true
    links:
      - "redis:redis"
      - "mongo:mongo"
      - "mysql:mysql"
    networks:
      - nursery
  redis:
    image: redis
    container_name: redis
    ports:
       - "6378:6379"
    volumes:
      - ~/ns/redis/data:/data
    command: "--requirepass $REDIS_AUTH"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - nursery
  mongo:
    image: mongo:6.0.1
    container_name: mongo
    ports:
      - "27016:27017"
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=nursery
    volumes:
      - ~/ns/mongo/data/db:/data/db
      - ~/ns/mongo/data/log:/var/log/mongo
    networks:
      - nursery
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=$DB_DATABASE{}
      - TZ=Asia/Shanghai
    ports:
      - "3305:3306"
    volumes:
      - ~/ns/mysql/db_data:/var/lib/mysql
      - ./data/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    security_opt:
      - seccomp:unconfined
    networks:
      - nursery
  nginx:
    image: nginx:latest
    environment:
      - TZ=Asia/Shanghai
    container_name: nginx
    ports:
      - "9999:80"
      - "9998:8081"
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/cert:/etc/nginx/cert
    links:
      - "api:nursery"
    networks:
      - nursery
networks:
  nursery: